# ASP.NET Core (.NET Framework)

# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:


- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
- task: MSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArchitecture: 'x64'
- task: ContainerBuild@0
  inputs:
    dockerRegistryServiceConnection: 'openshift_registry'
    repository: 'test/ms-app'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift cluster'
    cmd: 'oc -n openshift-windows-machine-config-operator rsh deploy/winc-ssh /usr/bin/ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /tmp/ssh/private-key.pem administrator@ip-10-0-152-156.us-east-2.compute.internal powershell "docker login -u admin -p sha256~TaoC1fWDdA2icQ6VVUHAMstUtiNzoFHmskxS7kbAyWQ default-route-openshift-image-registry.apps.cluster-f2ngn.f2ngn.sandbox753.opentlc.com & docker pull default-route-openshift-image-registry.apps.cluster-f2ngn.f2ngn.sandbox753.opentlc.com/test/ms-app"'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift cluster'
    cmd: 'oc rollout latest "deploy-config-example"'